header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    pattern: |
      Copyright \d{4} Canonical Ltd.
      See LICENSE file for licensing details.
  paths:
    - '**'
  paths-ignore:
    - '.github/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.txt'
    - '.jujuignore'
    - '.gitignore'
    - '.licenserc.yaml'
    - 'CODEOWNERS'
    - 'LICENSE'
    - 'trivy.yaml'
    - 'pyproject.toml'
    - 'zap_rules.tsv'
    - '**/*.md.j2'
    - '**/lib/**'
    - '**/templates/**'
    - 'charmed_bacula_server/snap/hooks/**'
    - '.readthedocs.yaml'
    - 'docs/**'
  comment: on-failure
